import assert from 'node:assert/strict';
import test from 'node:test';
import * as XLSX from 'xlsx';
import { parseLoyalisPresenceWorkbook } from './loyalisPresenceWorkbook';

test('parses the raw Loyalis workbook shape and filters to the selected period', () => {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(
    workbook,
    XLSX.utils.aoa_to_sheet([['A sheet without attendance headers']]),
    'Notes',
  );
  XLSX.utils.book_append_sheet(
    workbook,
    XLSX.utils.aoa_to_sheet([
      ['Report generated by attendance system'],
      [
        ' NIPY ',
        ' Nama ',
        'Departemen',
        ' Tanggal ',
        ' Jam kerja ',
        ' Scan masuk ',
        ' Scan pulang ',
      ],
      ['P-001', 'A Person', 'SDM', '01-07-2026', 'Tidak Hadir', 0.3125, '14:00:00'],
      ['P-001', 'A Person', 'SDM', '02-07-2026', 'MASUK', '07:57:46', '15:40:28'],
      ['P-001', 'A Person', 'SDM', '01-08-2026', 'MASUK', '08:00:00', '14:00:00'],
    ]),
    'Presensi Juli',
  );

  const bytes = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
  const parsed = parseLoyalisPresenceWorkbook(bytes, '2026-07');

  assert.equal(parsed.sheetName, 'Presensi Juli');
  assert.equal(parsed.sourceRowCount, 3);
  assert.equal(parsed.rows.length, 2);
  assert.equal(parsed.outsidePeriodCount, 1);
  assert.deepEqual(parsed.rows[0], {
    rowNumber: 3,
    nipy: 'P-001',
    name: 'A Person',
    department: 'SDM',
    date: '01-07-2026',
    dateIso: '2026-07-01',
    workStatus: 'Tidak Hadir',
    scanIn: '',
    scanOut: '',
    issues: [],
  });
  assert.equal(parsed.rows[1].scanIn, '07:57:46');
  assert.equal(parsed.rows[1].scanOut, '15:40:28');
});
