import { doc, getDoc, getDocs, collection, query, where, updateDoc } from 'firebase/firestore';

export interface PaySlipField {
  label: string;
  amount: number;
}

export async function syncActivityToPayslip(db: any, employeeId: string, period: string) {
  try {
    // 1. Check if payslip exists in PayrollSlipStates
    // Document ID is formatted as: YYYY_MM_employeeId
    const periodKey = period.replace('-', '_'); // Convert "2026-07" to "2026_07"
    const slipDocId = `${periodKey}_${employeeId}`;
    const slipRef = doc(db, 'PayrollSlipStates', slipDocId);
    const slipSnap = await getDoc(slipRef);

    if (!slipSnap.exists()) {
      // If the payslip does not exist yet, we do not need to do anything.
      // It will be calculated dynamically using the latest approved activities when generated by the admin or employee.
      return;
    }

    // 2. Fetch employee details to find jobCategory
    let jobCategory = '';
    const bcRef = doc(db, 'Employees_BlueCollar', employeeId);
    const bcSnap = await getDoc(bcRef);
    if (bcSnap.exists()) {
      jobCategory = bcSnap.data().employment?.jobCategory || '';
    } else {
      const empRef = doc(db, 'Employees', employeeId);
      const empSnap = await getDoc(empRef);
      if (empSnap.exists()) {
        const data = empSnap.data();
        jobCategory = data.employment_profile?.jobCategory || data.role || '';
      }
    }

    if (!jobCategory) {
      console.warn(`[payslipSync] Job category not found for employee: ${employeeId}`);
      return;
    }

    // 3. Query all approved activity reports for this employee and period
    const q = query(
      collection(db, 'ActivityReports'),
      where('employeeId', '==', employeeId),
      where('period', '==', period),
      where('status', '==', 'approved')
    );
    const reportsSnap = await getDocs(q);
    const reports = reportsSnap.docs.map(d => d.data());

    // 4. Update the earnings list
    const slipData = slipSnap.data();
    const earnings: PaySlipField[] = [...(slipData.earnings || [])];

    if (jobCategory === 'SATPAM') {
      // Count Satpam shifts
      let harianCount = 0;
      let jumatCount = 0;
      let lemburSendiriCount = 0;
      let lemburCoverCount = 0;

      reports.forEach(r => {
        const shiftType = r.shiftType || '';
        if (shiftType === 'Harian') harianCount++;
        else if (shiftType === 'Jumat & Libur') jumatCount++;
        else if (shiftType === 'Lembur Sendiri') lemburSendiriCount++;
        else if (shiftType === 'Lembur Cover') lemburCoverCount++;
      });

      const updateOrAddEarning = (label: string, amount: number) => {
        const idx = earnings.findIndex(e => e.label === label);
        if (idx > -1) {
          earnings[idx] = { ...earnings[idx], amount };
        } else {
          earnings.push({ label, amount });
        }
      };

      updateOrAddEarning('Vakasi Harian', harianCount * 12500);
      updateOrAddEarning('Jumat & Libur', jumatCount * 25000);
      updateOrAddEarning('Lembur Sendiri', lemburSendiriCount * 30000);
      updateOrAddEarning('Lembur Cover', lemburCoverCount * 50000);
    } else {
      // For non-Satpam, get spjEvents (kegiatanTotal) and activities (activityTotal)
      let spjEventsTotal = 0;
      try {
        const spjQ = query(
          collection(db, 'KegiatanSpj'),
          where('period', '==', period)
        );
        const spjSnap = await getDocs(spjQ);
        spjSnap.docs.forEach(d => {
          const data = d.data();
          const workerInfo = data.eventWorkers?.[employeeId];
          if (workerInfo) {
            spjEventsTotal += workerInfo.payGiven || 0;
          }
        });
      } catch (err) {
        console.error('[payslipSync] Error fetching KegiatanSpj:', err);
      }

      const activityTotal = reports.reduce((sum, r) => sum + (r.fee || 0), 0);
      const totalSpj = spjEventsTotal + activityTotal;

      const idx = earnings.findIndex(e => e.label === 'SPJ');
      if (idx > -1) {
        earnings[idx] = { ...earnings[idx], amount: totalSpj };
      } else {
        earnings.push({ label: 'SPJ', amount: totalSpj });
      }
    }

    // 5. Save updated earnings to PayrollSlipStates
    await updateDoc(slipRef, { earnings });
    console.log(`[payslipSync] Successfully synced activities to payslip for ${employeeId} (${period})`);
  } catch (err) {
    console.error(`[payslipSync] Error syncing activities to payslip for ${employeeId}:`, err);
  }
}
